plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'preview/**/*'

# I keep the length as short as possible without having too much pain.
# 80 is too much pain, but many disagree.
Layout/LineLength:
  Max: 100

# # Tests and Rake tasks may have long blocks.
# Metrics/BlockLength:
#   Exclude:
#     - '**/Rakefile'
#     - '**/*.rake'
#     - '**/test/**/*_test.rb'

# Metrics/ClassLength:
#   Exclude:
#     - '**/test/**/*_test.rb'
